### ISSUE TITLE
Support for nvcr.io/nvidia/pytorch:24.01-py3

### ISSUE THREAD

**Issue by clessig** [singularityhub/shpc-registry#194]
**Is your feature request related to a problem? Please describe.**

Missing pytorch:24.01 container.

**Describe the solution you'd like**

SHPC adds support for http://nvcr.io/nvidia/pytorch:24.01-py3

**Describe alternatives you've considered**

[nvcr.io/nvidia/pytorch:24.01-py3](http://nvcr.io/nvidia/pytorch:24.01-py3) provides torch 2.2. which has important improvements. JUWELS-BOOSTER package will likely take months and pip install does not work there due to network config.

**Comment by vsoch** [comment]
Issue transferred to registry.

**Comment by vsoch** [comment]
@clessig I don't see access to that page, I think the latest public is still 23.09-py3. Is that suitable?

**Comment by clessig** [comment]
NVIDIA lists a newer one: https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch/tags. 

I think only the 24.x containers have torch 2.2 which has some significant performance improvements.

**Comment by vsoch** [comment]
Gotcha, please check out #195 I think I added it.
