### ISSUE TITLE
broken link 404 to update_biocontainers.py

### ISSUE THREAD

**Issue by SomePersonSomeWhereInTheWorld** [singularityhub/shpc-registry#226]
In the [README](https://github.com/singularityhub/shpc-registry/tree/main?tab=readme-ov-file), the link for "We have a [script](https://github.com/singularityhub/shpc-registry/blob/main/.github/scripts/update_biocontainers.py) that will generate" is broken.

**Comment by vsoch** [comment]
Thanks - typo and fixed! https://github.com/singularityhub/shpc-registry/commit/3c866e564c94c64722a4b67ff1be1e189e77b8ee
