### ISSUE TITLE
container.yaml with no aliases

### ISSUE THREAD

**Issue by muffato** [singularityhub/shpc-registry#32]
When reviewing some of the new containers, I found that some have no aliases, e.g. [quay.io/biocontainers/emboss/container.yaml](https://github.com/singularityhub/shpc-registry/blob/9ff92fbaa4c449ed8853426566a33206f62c0290/quay.io/biocontainers/emboss/container.yaml) and [quay.io/biocontainers/tabix/container.yaml](https://github.com/singularityhub/shpc-registry/blob/9ff92fbaa4c449ed8853426566a33206f62c0290/quay.io/biocontainers/tabix/container.yaml) – already mentioned in #31 – but also [infernal](https://github.com/singularityhub/shpc-registry/blob/9ff92fbaa4c449ed8853426566a33206f62c0290/quay.io/biocontainers/infernal/container.yaml). Maybe the import script could skip the count threshold if no commands are left ?

**Comment by vsoch** [comment]
@muffato there isn't a hard threshold for a count - e.g., _all_ binaries under a count of 10 are added, and then the next 25, whatever they may be in the sorted list. Looking at the cache for tabix:

https://github.com/singularityhub/shpc-registry-cache/blob/main/quay.io/biocontainers/t/tabix:1.11--hdfd78af_0.json

I do believe this is a bug! If you have some bandwidth to help, might you be able to look into the bug? I suspect what is happening is that we have an alias in tabix that wasn't in the global counts, so when we filter here: https://github.com/singularityhub/shpc-registry/blob/9ff92fbaa4c449ed8853426566a33206f62c0290/.github/scripts/update_biocontainers.py#L96-L97 it doesn't include it. The fix I think would be to test on this specific container, and then run the entire script again to regenerate the files!

**Comment by vsoch** [comment]
oup! I see the bug!

**Comment by muffato** [comment]
Hi @vsoch . I don't remember: how did you make the selection of containers for building the cache ? For instance, tophat is in the [registry](https://github.com/singularityhub/shpc-registry/blob/main/quay.io/biocontainers/tophat/container.yaml) and was added by #36, but it's not in the cache: https://github.com/singularityhub/shpc-registry-cache/tree/main/quay.io/biocontainers/t

**Comment by vsoch** [comment]
Here is the logic that you seek!

https://github.com/singularityhub/shpc-registry-cache/blob/511266c7ad4a1cb1718721ffc17ea4ec4cdf75b4/.github/scripts/update_biocontainers.py#L80-L82

We use those same lines again in the shpc-registry equivalent update script, going over the tags once more and adding containers (without aliases in the cache) just as not having any aliases. That's here. https://github.com/singularityhub/shpc-registry/blob/319064ee279e0b0eee92a00a17f960968b4d19a0/.github/scripts/update_biocontainers.py#L195-L200

And that script I'll have some tweaks for the alias issue we are discussing in the other thread.

**Comment by muffato** [comment]
Thanks. So why is `tophat` not in the cache ?

**Comment by vsoch** [comment]
Tophat isn’t in the cache because the dumping of the container archive failed - you could try running it locally to see if it works - it’s usually permissions issues for paths or size in the runner.

So this means we have tophat in the registry, but devoid of aliases.

**Comment by muffato** [comment]
Yep, tophat works:
```
$ wget https://depot.galaxyproject.org/singularity/tophat%3A2.1.1--py35_0
--2022-11-02 08:16:40--  https://depot.galaxyproject.org/singularity/tophat%3A2.1.1--py35_0
Resolving depot.galaxyproject.org (depot.galaxyproject.org)... 128.118.250.14
Connecting to depot.galaxyproject.org (depot.galaxyproject.org)|128.118.250.14|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 68231168 (65M) [application/octet-stream]
Saving to: ‘tophat:2.1.1--py35_0’

tophat:2.1.1--py35_0                    100%[===============================================================================>]  65.07M  11.6MB/s    in 7.7s    

2022-11-02 08:16:48 (8.48 MB/s) - ‘tophat:2.1.1--py35_0’ saved [68231168/68231168]

$ singularity exec tophat\:2.1.1--py35_0 ls /usr/local/bin | head
WARNING: Skipping mount /software/singularity-v3.9.0/var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
2to3
2to3-3.5
activate
bam2fastx
bam_merge
bed_to_juncs
c_rehash
captoinfo
clear
conda
```

**Comment by vsoch** [comment]
okay closing here - the containers with missing aliases are now populated:

- https://github.com/singularityhub/shpc-registry/blob/main/quay.io/biocontainers/tabix/container.yaml
- https://github.com/singularityhub/shpc-registry/blob/main/quay.io/biocontainers/emboss/container.yaml
